services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: premiummen_db
    environment:
      POSTGRES_DB: premiummen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - premiummen_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: premiummen_app
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/premiummen
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password123
      PGDATABASE: premiummen
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - premiummen_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  premiummen_network:
    driver: bridge

volumes:
  postgres_data: